### ISSUE TITLE
how to change wallpaper

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#12]
trying to change it to some jps in my home/pictures but its not working. 

file i am editing is default-theme.lua
```

  theme.wallpaper = '/home/najam/Pictures/mexican.jpg'
  --theme.wallpaper = '#000000'
```

if i set wallpaper to color code it turns black but for some reason cant show image

**Comment by PapyElGringo** [comment]
The theme can only be used to set the colors. In fact my config is not mean to be used with wallpaper because the background will soon be used to display shortcuts to start recently used apps on the tags.

But if you want to change it in the mean time go edit rc.lua line 26

and set a function from https://awesomewm.org/doc/api/libraries/gears.wallpaper.html

**Comment by najamsk** [comment]
done line 26 did the trick with the help of above documentation.
